import React from 'react';

import type {NextPage} from 'next';
import Head from 'next/head';

import TestComponent from '@/components/TestComponent';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TestComponent className="text-red-500" />
    </div>
  );
};

export default Home;
